---
- name: Converge
  hosts: all
  become: true

  vars:
    pimpmylog_grant_all_privs: true
    pimpmylog_install_dir: /var/www/html/pimpmylog
    php_default_version_debian: "7.2"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: geerlingguy.pimpmylog

  post_tasks:
    - name: Ensure pimpmylog is running on the specified port.
      uri:
        url: "http://127.0.0.1/pimpmylog/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
